[package]
name = 'hollow'
description = 'attr macro to swallow the body of fn attached to'
categories = ['development-tools::debugging']
version = '0.1.0'
edition = '2021'
license = 'BSD-3-Clause'
authors = ['Blair Noctis <n@sail.ng>']

[lib]
proc-macro = true
